# Generated by Django 4.1.7 on 2023-06-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('tc_kimlik', models.CharField(max_length=11, unique=True)),
                ('profil_fotografi', models.ImageField(upload_to='driver_profile')),
                ('arac_marka_model', models.CharField(max_length=100)),
                ('calistigi_sehirler', models.CharField(max_length=200)),
                ('gunluk_tur_fiyati', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
