# Generated by Django 4.1.7 on 2023-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='telefon',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
