# Generated by Django 4.1.7 on 2023-06-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='adres',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default=' ', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
