# Generated by Django 4.1.7 on 2023-06-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driver_username_alter_driver_profil_fotografi'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='confirmpassword',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
