# Generated by Django 4.1.7 on 2023-06-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driver_confirmpassword_driver_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
