# Generated by Django 4.1.7 on 2023-06-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_driver_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='confirmpassword',
        ),
    ]
