# Generated by Django 4.1.7 on 2023-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_remove_driver_availability_driver_availability_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
