# Generated by Django 4.1.7 on 2023-06-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0013_alter_driver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='aracResimleri',
            field=models.ImageField(default=' ', upload_to='images/'),
            preserve_default=False,
        ),
    ]
