# Generated by Django 4.1.7 on 2023-06-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_driver_aracresimleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='AracResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='aracResimleri',
        ),
        migrations.AddField(
            model_name='driver',
            name='arac_resimleri',
            field=models.ManyToManyField(blank=True, to='driver.aracresim'),
        ),
    ]
