# Generated by Django 4.1.7 on 2023-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_aracresim_remove_driver_aracresimleri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='arac_resimleri',
        ),
        migrations.AddField(
            model_name='driver',
            name='arac_resimleri',
            field=models.FileField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
