# Generated by Django 4.1.7 on 2023-06-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0016_remove_driver_arac_resimleri_driver_arac_resimleri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AracResim',
        ),
    ]
