# Generated by Django 4.1.7 on 2023-06-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_surucu'),
        ('driver', '0020_remove_driver_arac_resimleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_surucu', to='reservation.reservation'),
        ),
    ]
