# Generated by Django 4.1.7 on 2023-06-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_kullanici'),
        ('driver', '0021_driver_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_reservation', to='reservation.reservation'),
        ),
    ]
