# Generated by Django 4.1.7 on 2023-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nUser', '0002_nuser_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuser',
            name='password1',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='nuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='nuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
