# Generated by Django 4.1.7 on 2023-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nUser', '0003_nuser_password1_alter_nuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuser',
            name='password1',
        ),
        migrations.AlterField(
            model_name='nuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
