# Generated by Django 4.1.7 on 2023-06-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_kullanici'),
        ('nUser', '0007_alter_nuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuser',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reservation'),
        ),
    ]
