# Generated by Django 4.1.7 on 2023-06-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nUser', '0008_nuser_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuser',
            name='isDriver',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
