# Generated by Django 4.1.7 on 2023-06-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nUser', '0009_nuser_isdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuser',
            name='isDriver',
            field=models.BooleanField(default=False),
        ),
    ]
