# Generated by Django 4.1.7 on 2023-06-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0020_remove_driver_arac_resimleri'),
        ('reservation', '0002_alter_reservation_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='surucu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
    ]
