# Generated by Django 4.1.7 on 2023-06-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0021_driver_reservation'),
        ('reservation', '0003_alter_reservation_surucu'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='onay_durum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='surucu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_surucu', to='driver.driver'),
        ),
    ]
