# Generated by Django 4.2.2 on 2023-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fiyat',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
