# Generated by Django 4.2.2 on 2023-06-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation_fiyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='fiyat',
        ),
    ]
