# Generated by Django 4.2.2 on 2023-06-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_alter_reservation_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tamam_durum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='fiyat',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
